### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by adamhstewart** [Gizra-Presentations/client-training#1]

**Comment by IshaDakota** [comment]
<img width="1062" alt="issues_ _gizra_jep-findyoursummer" src="https://cloud.githubusercontent.com/assets/688507/25858363/36e7a1f4-34a1-11e7-878e-e6891235503d.png">

**Comment by IshaDakota** [comment]
<img width="397" alt="dashboard___live_gizra_productivity" src="https://cloud.githubusercontent.com/assets/688507/25858898/8d0d4380-34a2-11e7-95ae-1b9ca7a83001.png">

**Comment by IshaDakota** [comment]
<img width="1270" alt="fys_v2_0" src="https://cloud.githubusercontent.com/assets/688507/25859924/9ed685ec-34a5-11e7-89f0-f2725ce2c4e2.png">

<img width="1072" alt="milestones_-_gizra_jep-findyoursummer" src="https://cloud.githubusercontent.com/assets/688507/25859968/b538af90-34a5-11e7-9f34-cc5e2aed60ab.png">

**Comment by liatsade** [comment]
@IshaDakota the presentation looks great. 
Need to blur the names of the projects / clients in the images.

**Comment by amitaibu** [comment]
@IshaDakota handy! btw, a pro tip -- once you upload an image, you don't really need to submit the comment. The file is already uploaded. 😈

**Comment by amitaibu** [comment]
To follow up on @liatsade comment: You can keep the devs name, and circuit related project, but indeed blur other project names.

**Comment by adamhstewart** [comment]
^^ fixed.
